---
title: "Artigos"
format: html
sidebar: pt-articles
---

<style>
  body {
    background-repeat: repeat-y;
    background-size: cover;
    background-attachment: fixed;
    background-position: top center;
    position: relative;
    z-index: 0;
  }

  .background-overlay {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(255, 255, 255, 0.85);
    z-index: -1;
  }
</style>

::: {layout-ncol="2"}
::: {style="display: block;"}
### Verificar versões do conjunto de dados
- [Verificar as versões disponíveis da FFB](/pt/articles/check_ffb_versions.qmd)

::: {style="display: block;"}
:::
### Baixar e analisar dados da FFB
- [Baixar a lista de espécies da FFB](/pt/articles/download_ffb_dataset.qmd)
- [Analisar arquivos Darwin Core da FFB](/pt/articles/parse_ffb_dwca.qmd)

::: {style="display: block;"}
:::
### Navegar e filtrar a lista de espécies
- [Filtrar e recuperar registros da lista de espécies](/pt/articles/filter_ffb_records.qmd)

::: {style="display: block;"}
:::
### Resolver e explorar a taxonomia
- [Resolver sua própria lista de nomes de espécies](/pt/articles/resolve_species_names.qmd)
- [Explorar a hierarquia taxonômica](/pt/articles/explore_taxonomic_hierarchy.qmd)

::: {style="display: block;"}
:::
### Curar novos registros
- [Curar e descrever novos registros](/pt/articles/curate_ffb_descriptions.qmd)
:::
:::
