---
title: "Articles"
format: html
---

<style>
  body {
    background-repeat: repeat-y;
    background-size: cover;
    background-attachment: fixed;
    background-position: top center;
    position: relative;
    z-index: 0;
  }

  .background-overlay {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(255, 255, 255, 0.85);
    z-index: -1;
  }
</style>

::: {layout-ncol="2"}
::: {style="display: block;"}
### Check dataset versions
- [Check available FFB dataset versions](/articles/check_ffb_versions.qmd)

::: {style="display: block;"}
:::
### Download and parse FFB data
- [Download the FFB checklist](/articles/download_ffb_dataset.qmd)
- [Parse FFB Darwin Core Archives](/articles/parse_ffb_dwca.qmd)

::: {style="display: block;"}
:::
### Browse and filter the checklist
- [Filter and retrieve checklist records](/articles/filter_ffb_records.qmd)

::: {style="display: block;"}
:::
### Resolve and explore taxonomy
- [Resolve your own species names](/articles/resolve_species_names.qmd)
- [Explore the taxonomic hierarchy](/articles/explore_taxonomic_hierarchy.qmd)

::: {style="display: block;"}
:::
### Curate new records
- [Curate and describe new records](/articles/curate_ffb_descriptions.qmd)
:::
:::
